version: '3.8'

services:
  app:
    image: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: ${APP_NAME}-app
    environment:
      - APP_DATA_DIR=/app/data
    volumes:
      - ${DATA_DIR}:/app/data
    ports:
      - "${APP_PORT}:8080"
