version: '3.8'

services:
  app:
    image: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    working_dir: '/app/src'
    entrypoint: ['/app/src/start.sh']
    container_name: ${APP_NAME}-app
    environment:
      - APP_DATA_DIR=/app/data
    volumes:
      - ${DATA_DIR}:/app/data
      - ./src:/app/src
    ports:
      - "${APP_PORT}:8080"
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
#      - ./configs/app.nginx:/etc/nginx/nginx.conf:ro
      - ./configs/app.nginx:/etc/nginx/conf.d/app.conf:ro
      - ${DATA_DIR}:/var/www/app
    depends_on:
      - app
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend



networks:
  frontend:
  backend: